// packages/react/src/components/organisms/SfSidebar/index.jsx
import React, { useEffect, useRef } from 'react';
import classnames from 'classnames';
import { SfOverlay, SfCircleIcon, SfHeading } from '../../atoms';
import { CSSTransition } from 'react-transition-group';
import PropTypes from 'prop-types';
import '../../utilities/transitions/transitions.scss';
import '@storefront-ui/shared/styles/components/SfSidebar.scss';

export const SfSidebar = ({
  classname,
  headingTitle,
  headingSubtitle,
  headingLevel,
  button,
  visible,
  overlay,
  onclose,
}) => {
  const ref = useRef(null);

  useEffect(() => {
    document.addEventListener('keydown', keydownHandler);
    return () => {
      document.removeEventListener('keydown', keydownHandler);
    };
  }, []);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (visible) {
      document.body.classList.add('sf-sidebar--has-scroll-lock');
    } else {
      document.body.classList.remove('sf-sidebar--has-scroll-lock');
    }
  }, [visible]);

  const visibleOverlay = () => {
    return visible && overlay;
  };
  const keydownHandler = (e) => {
    if (e.key === 'Escape' || e.key === 'Esc' || e.keyCode === 27) {
      onclose();
    }
  };
  const position = () => {
    return ref && ref.current && ref.current.classList.contains('sf-sidebar--right') ? 'right' : 'left';
  };

  return (
    <div ref={ref} className={classnames('sf-sidebar', classname)}>
      <SfOverlay visible={visibleOverlay()} onclick={onclose} />
      <CSSTransition in={visible} classNames={`slide-${position()}`} timeout={300} unmountOnExit>
        <aside className="sf-sidebar__aside">
          <div className="sf-sidebar__content">
            <slot name="title">
              <SfHeading
                title={headingTitle}
                subtitle={headingSubtitle}
                level={headingLevel}
                className="sf-heading--left sf-heading--no-underline sf-sidebar__title"
              />
            </slot>
            <slot />
          </div>
          <slot name="circle-icon">
            {button && <SfCircleIcon size="14px" icon="cross" classname="sf-sidebar__circle-icon" onclick={onclose} />}
          </slot>
        </aside>
      </CSSTransition>
    </div>
  );
};

SfSidebar.propTypes = {
  headingTitle: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  headingSubtitle: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  headingLevel: PropTypes.number,
  button: PropTypes.bool,
  visible: PropTypes.bool,
  overlay: PropTypes.bool,
};

SfSidebar.defaultProps = {
  headingTitle: 'title',
  headingSubtitle: '',
  headingLevel: 1,
  button: true,
  visible: false,
  overlay: true,
};

// packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
<template>
  <div class="sf-sidebar" :class="[staticClass, className]">
    <SfOverlay :visible="visibleOverlay" />
    <transition :name="transitionName">
      <aside
        v-if="visible"
        ref="sidebarAside"
        v-focus-trap
        v-click-outside="checkPersistence"
        class="sf-sidebar__aside"
      >
        <!--@slot Use this slot to place content inside the modal bar.-->
        <div ref="contentTopSmartphone" class="smartphone-only">
          <slot name="bar">
            <SfBar :title="title" :back="true" @click:back="close" />
          </slot>
        </div>
        <!--@slot Use this slot to replace close icon.-->
        <slot name="circle-icon" v-bind="{ close, button }">
          <SfCircleIcon
            v-if="button"
            icon-size="12px"
            aria-label="Close sidebar"
            icon="cross"
            class="sf-sidebar__circle-icon desktop-only"
            @click="close"
          />
        </slot>
        <div
          v-if="title || hasTop"
          ref="contentTopDesktop"
          class="sf-sidebar__top"
        >
          <!--@slot Use this slot to replace SfHeading component.-->
          <slot name="title" v-bind="{ title, subtitle, headingLevel }">
            <SfHeading
              v-if="title"
              :title="title"
              :description="subtitle"
              :level="headingLevel"
              class="sf-heading--left sf-heading--no-underline sf-sidebar__title"
            />
          </slot>
          <!--@slot Use this slot to add sticky top content.-->
          <slot name="content-top" />
        </div>
        <SfScrollable
          show-text=""
          hide-text=""
          :max-content-height="setMaxHeight"
        >
          <div ref="content" class="sf-sidebar__content">
            <!--@slot Use this slot to add SfSidebar content.-->
            <slot />
          </div>
        </SfScrollable>
        <!--@slot Use this slot to place content to sticky bottom.-->
        <div v-if="hasBottom" ref="contentBottom" class="sf-sidebar__bottom">
          <slot name="content-bottom" />
        </div>
      </aside>
    </transition>
  </div>
</template>
<script>
import { focusTrap } from "../../../utilities/directives/";
import { clickOutside } from "../../../utilities/directives/";
import { disableBodyScroll, clearAllBodyScrollLocks } from "body-scroll-lock";
import { isClient } from "../../../utilities/helpers";
import SfBar from "../../molecules/SfBar/SfBar.vue";
import SfCircleIcon from "../../atoms/SfCircleIcon/SfCircleIcon.vue";
import SfOverlay from "../../atoms/SfOverlay/SfOverlay.vue";
import SfHeading from "../../atoms/SfHeading/SfHeading.vue";
import SfScrollable from "../../molecules/SfScrollable/SfScrollable.vue";
export default {
  name: "SfSidebar",
  directives: { focusTrap, clickOutside },
  components: {
    SfBar,
    SfCircleIcon,
    SfOverlay,
    SfHeading,
    SfScrollable,
  },
  props: {
    /**
     * The sidebar's title
     */
    title: {
      type: String,
      default: "",
    },
    /**
     * The sidebar's subtitle
     */
    subtitle: {
      type: String,
      default: "",
    },
    /**
     * The heading's level
     */
    headingLevel: {
      type: Number,
      default: 3,
    },
    /**
     * The close button
     */
    button: {
      type: Boolean,
      default: true,
    },
    /**
     * The sidebar's visibility
     */
    visible: {
      type: Boolean,
      default: false,
    },
    /**
     * The overlay's visibility
     */
    overlay: {
      type: Boolean,
      default: true,
    },
    /**
     * If true clicking outside will not dismiss the sidebar
     */
    persistent: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      position: "left",
      staticClass: null,
      className: null,
      setMaxHeight: "",
    };
  },
  computed: {
    visibleOverlay() {
      return this.visible && this.overlay;
    },
    transitionName() {
      return "sf-slide-" + this.position;
    },
    hasTop() {
      return this.$slots.hasOwnProperty("content-top");
    },
    hasBottom() {
      return this.$slots.hasOwnProperty("content-bottom");
    },
  },
  watch: {
    visible: {
      handler(value) {
        if (!isClient) return;
        if (value) {
          this.$nextTick(() => {
            disableBodyScroll(this.$refs.sidebarAside);
            console.log(
              window.innerHeight,
              this.$refs.contentTopDesktop.offsetHeight,
              this.$refs.contentBottom.offsetHeight
            );
            if (this.$slots.default) {
              this.setMaxHeight = `${(
                window.innerHeight -
                this.$refs.contentTopSmartphone.offsetHeight -
                this.$refs.contentTopDesktop.offsetHeight -
                this.$refs.contentBottom.offsetHeight
              ).toString()}px`;
              console.log(this.setMaxHeight);
            }
          });
          document.addEventListener("keydown", this.keydownHandler);
        } else {
          clearAllBodyScrollLocks();
          document.removeEventListener("keydown", this.keydownHandler);
        }
      },
      immediate: true,
    },
  },
  mounted() {
    this.classHandler();
  },
  updated() {
    this.classHandler();
  },
  methods: {
    close() {
      this.$emit("close");
    },
    checkPersistence() {
      if (!this.persistent) this.close();
    },
    keydownHandler(e) {
      if (e.key === "Escape" || e.key === "Esc" || e.keyCode === 27) {
        this.close();
      }
    },
    classHandler() {
      let update = false;
      if (this.staticClass !== this.$vnode.data.staticClass) {
        this.staticClass = this.$vnode.data.staticClass;
        update = true;
      }
      if (this.className !== this.$vnode.data.class) {
        this.className = this.$vnode.data.class;
        update = true;
      }
      if (update) {
        this.position =
          [this.staticClass, this.className].toString().search("--right") > -1
            ? "right"
            : "left";
      }
    },
  },
};
</script>
<style lang="scss">
@import "~@storefront-ui/shared/styles/components/organisms/SfSidebar.scss";
</style>
